// مسار الملف: js/main.js
import { ENV } from './config/env.js';
import { db, auth } from './core/firebase-init.js';
import { UI } from './utils/ui.js';
import { Auth } from './auth/auth.js';
import { Services } from './core/services.js';
import { Scanner } from './modules/scanner.js';
import { Settings } from './modules/settings.js';
import { mountEnterpriseOperations } from './modules/enterprise-operations.js';
import { mountFactoryOSGlobal } from './modules/factory-os-global-v30.js';
import { TPM_DOMAIN, getTPMPillar } from './core/tpm-domain.js';
import { normalizeRole, roleLabel, canAccessRole } from './core/role-policy.js';
console.log(`🚀 FACTORY OS - V${ENV.APP_VERSION} ENTERPRISE CORE`);
window.auth=auth;window.db=db;window.TPM_DOMAIN=TPM_DOMAIN;window.getTPMPillar=getTPMPillar;window.normalizeTPMRole=normalizeRole;window.getTPMRoleLabel=roleLabel;
const loadStylesheet=(id,href)=>{if(document.getElementById(id))return;const link=document.createElement('link');link.id=id;link.rel='stylesheet';link.href=href;document.head.appendChild(link)};
loadStylesheet('enterprise-v26-theme','./css/enterprise-v26.css?v=29');loadStylesheet('mobile-v27-theme','./css/mobile-v27.css?v=29');loadStylesheet('ux-v28-polish','./css/ux-v28-polish.css?v=1');loadStylesheet('factory-os-executive-v32','./css/factory-os-executive-v32.css?v=1');
function configureCharts(){if(!window.Chart||window.__factoryChartsConfigured)return;window.__factoryChartsConfigured=true;const C=window.Chart;C.defaults.font.family="Cairo, sans-serif";C.defaults.font.size=11;C.defaults.color="#46525f";C.defaults.responsive=true;C.defaults.maintainAspectRatio=false;C.defaults.plugins.legend.position='bottom';C.defaults.plugins.legend.labels.usePointStyle=true;C.defaults.plugins.legend.labels.boxWidth=8;C.defaults.plugins.legend.labels.padding=16;C.defaults.plugins.tooltip.backgroundColor='#20303f';C.defaults.plugins.tooltip.titleColor='#fff';C.defaults.plugins.tooltip.bodyColor='#fff';C.defaults.plugins.tooltip.padding=10;C.defaults.plugins.tooltip.cornerRadius=7;C.defaults.scale.grid.color='rgba(83,101,117,.12)';C.defaults.scale.border.color='rgba(83,101,117,.22)';C.defaults.scale.ticks.color='#778391';}
window.renderProfileAndSettings=()=>Settings.renderProfileAndSettings();window.switchSettingsTab=(id,button)=>Settings.switchSettingsTab(id,button);window.openMyFullProfile=()=>Settings.openMyFullProfile();window.updateProfilePic=e=>Settings.updateProfilePic(e);window.saveApiKeys=()=>Settings.saveApiKeys();window.enableApiKeysEdit=()=>Settings.enableApiKeysEdit();
window.showScreen=id=>UI.showScreen(id);window.goBack=()=>UI.goBack();window.showToast=m=>UI.showToast(m);window.toggleSidebar=()=>UI.toggleSidebar();window.toggleDarkMode=()=>UI.toggleDarkMode();window.sanitizeInput=v=>UI.sanitizeInput(v);window.uniqueNumericId=()=>UI.uniqueNumericId();window.login=()=>Auth.login();window.signup=()=>Auth.signup();window.logout=()=>Auth.logout();window.biometricLogin=()=>Auth.biometricLogin();window.scanBarcodeFromImage=e=>Scanner.scanBarcodeFromImage(e);window.forceAcceptBarcode=t=>Scanner.forceAcceptBarcode(t);
window.syncRecord=(p,d)=>Services.syncRecord(p,d);window.deleteRecord=p=>Services.deleteRecord(p);window.logAction=a=>Services.logAction(a,window.currentUser?.name);window.uploadImageToStorage=(f,o={})=>Services.uploadImageToStorage(f,o);window.processAndEnhanceImage=(f,c)=>Services.processAndEnhanceImage(f,c);window.fetchGeminiAPI=(p,b)=>Services.fetchGeminiAPI(p,b);
window.TPMAccess={role(){return normalizeRole(window.currentUser?.role)},label(){return roleLabel(this.role())},canAccess(id){if(['loginScreen','signupScreen'].includes(id))return true;if(!window.auth?.currentUser)return false;return canAccessRole(this.role(),id)},require(...roles){const ok=roles.map(normalizeRole).includes(this.role());if(!ok)this.deny();return ok},deny(){UI.showToast('🔒 لا تملك صلاحية الوصول إلى هذه المساحة.');return false}};window.hasRole=(...allowed)=>allowed.map(normalizeRole).includes(normalizeRole(window.currentUser?.role));
function installBackHistoryGuard(){const original=UI.goBack.bind(UI);UI.goBack=()=>{if(UI.screenHistory.length>1)return original();return undefined};}
window.addEventListener('load',()=>{configureCharts();const legacy=window.showScreen;if(typeof legacy==='function'&&!legacy.__tpmGuarded){const guarded=id=>{if(!window.TPMAccess.canAccess(id))return window.TPMAccess.deny();return legacy(id)};guarded.__tpmGuarded=true;window.showScreen=guarded}window.showToast=m=>UI.showToast(m);installBackHistoryGuard();mountEnterpriseOperations();mountFactoryOSGlobal()});
const canonicalizeSessionRole=()=>{if(!window.currentUser)return;const canonical=normalizeRole(window.currentUser.role);if(window.currentUser.role!==canonical)window.currentUser.role=canonical;window.currentUser.roleLabel=roleLabel(canonical);document.querySelectorAll('[data-current-role]').forEach(el=>el.textContent=roleLabel(canonical))};
window.addEventListener('DOMContentLoaded',()=>{if(localStorage.getItem('tpm_theme')==='light')document.body.classList.add('light-theme');canonicalizeSessionRole();setTimeout(canonicalizeSessionRole,500);setTimeout(canonicalizeSessionRole,1500)});auth.onAuthStateChanged(()=>{setTimeout(canonicalizeSessionRole,0);setTimeout(canonicalizeSessionRole,300)});
